### ISSUE TITLE
problem with saving files

### ISSUE THREAD

**Issue by saiganesh2506** [AlexLionne/MDAvatars#4]
the images are not saved properly , there are cut and **only** _hair_ is visible.

android version : 5.1.1 (oxygen OS)

![screenshot_2016-03-17-01-45-52](https://cloud.githubusercontent.com/assets/17888516/13827652/c668aeca-ebe3-11e5-940b-25e7e4919f24.png)

![2016-03-16](https://cloud.githubusercontent.com/assets/17888516/13827672/deb6ba44-ebe3-11e5-8568-84225bf1ee4e.png)

**Comment by AlexLionne** [comment]
Its fix with the latest 1.0.4 Version, 
Thanks,

**Comment by saiganesh2506** [comment]
sadly the issue still persists in the **1.0.4 version** too.

![screenshot_2016-03-17-15-33-38](https://cloud.githubusercontent.com/assets/17888516/13842812/43cb1ade-ec56-11e5-9283-82fe54639e5b.png)

![screenshot_2016-03-17-15-33-50](https://cloud.githubusercontent.com/assets/17888516/13842826/4f68d048-ec56-11e5-9b81-b77dd453ee7b.png)

![screenshot_2016-03-17-15-34-59](https://cloud.githubusercontent.com/assets/17888516/13842834/5607aef6-ec56-11e5-8e31-307b5989c4b3.png)

**Comment by AlexLionne** [comment]
okay thx for reporting I'll see what I can do
